[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="gooey-bridge"
    RemoteNickFormat="[{PROTOCOL}] {NOPINGNICK}: "
    ShowJoinPart=false

[slack]
    [slack.terasology]
        Token="[TOKEN]"
        IconURL="https://robohash.org/{NICK}.png?size=96x96"
        NickFormatter="plain"
        NicksPerRow=4
        EditDisable=false
        PrefixMessagesWithNick=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false

[discord]
    [discord.terasology]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"

    [discord.destsol]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"

    [discord.ai]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"

    [discord.geneticbees]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"

    [discord.restoration]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"

    [discord.lightandshadow]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"
      
	[discord.module-site]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"
        
	[discord.renegades-world]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"
        
	
	[discord.renegades-multi]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"

	[discord.launcher]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"

    [discord.rendering]
        Token="[TOKEN]"
        Server="Terasology"
        ShowEmbeds=false
        WebhookURL="URL"
        EditDisable=false
        IgnoreNicks="GitHub"
        RemoteNickFormat="[{PROTOCOL}] {NICK}"
        ShowJoinPart=false
        IconURL="https://robohash.org/{NICK}.png?size=96x96"

[[gateway]]
name="terasology"
enable=true
    [[gateway.inout]]
    account="irc.freenode"
    channel="#terasology"

    [[gateway.inout]]
    account="slack.terasology"
    channel="general"

    [[gateway.inout]]
    account="discord.terasology"
    channel="terasology"

[[gateway]]
name="dest-sol"
enable=true
    [[gateway.inout]]
    account="irc.freenode"
    channel="#destination-sol"

    [[gateway.inout]]
    account="slack.terasology"
    channel="destination-sol"

    [[gateway.inout]]
    account="discord.destsol"
    channel="destination-sol"

[[gateway]]
name="terasology-ai"
enable=true
    [[gateway.inout]]
    account="slack.terasology"
    channel="ai"

    [[gateway.inout]]
    account="discord.ai"
    channel="ai"

[[gateway]]
name="terasology-geneticbees"
enable=true
    [[gateway.inout]]
    account="slack.terasology"
    channel="genetic-bees"

    [[gateway.inout]]
    account="discord.geneticbees"
    channel="genetic-bees"

[[gateway]]
name="terasology-renegades-multi"
enable=true
    [[gateway.inout]]
    account="slack.terasology"
    channel="metal-renegades-multi"

    [[gateway.inout]]
    account="discord.renegades-multi"
    channel="metal-renegades-multi"
	
[[gateway]]
name="terasology-renegades-world"
enable=true
    [[gateway.inout]]
    account="slack.terasology"
    channel="metal-renegades-world"

    [[gateway.inout]]
    account="discord.renegades-world"
    channel="metal-renegades-world"
	


[[gateway]]
name="terasology-restoration"
enable=true
    [[gateway.inout]]
    account="slack.terasology"
    channel="restoration-100"

    [[gateway.inout]]
    account="discord.restoration"
    channel="restoration-100"


[[gateway]]
name="terasology-lightandshadow"
enable=true
    [[gateway.inout]]
    account="slack.terasology"
    channel="light-and-shadow"

    [[gateway.inout]]
    account="discord.lightandshadow"
    channel="light-and-shadow"
	

[[gateway]]
name="terasology-modulesite"
enable=true
    [[gateway.inout]]
    account="slack.terasology"
    channel="module-site"

    [[gateway.inout]]
    account="discord.module-site"
    channel="module-site"

[[gateway]]
name="terasology-launcher"
enable=true
    [[gateway.inout]]
    account="slack.terasology"
    channel="launcher"

    [[gateway.inout]]
    account="discord.launcher"
    channel="launcher"
    
[[gateway]]
name="terasology-rendering"
enable=true
    [[gateway.inout]]
    account="slack.terasology"
    channel="rendering"

    [[gateway.inout]]
    account="discord.rendering"
    channel="rendering"
